/* GENERATED BY tools/gen_cmm_shim.py -- DO NOT EDIT BY HAND.
 *
 * Boxed FFI shims between the Cmm code generator and the Rex C runtime.
 *
 * gmm cannot receive a C `double` or a struct return value from a foreign
 * call, so every Rex value crosses the boundary as a `W_` pointer to a
 * heap-allocated `RexValue`.  These wrappers do that boxing in C, where the
 * real runtime signatures are available.
 */

#include "rex_rt.h"
#include "rex_cmm_shim.h"

#include <stdlib.h>
#include <string.h>

/* Allocate and populate one result box. */
W_ rex_cmm_mkbox(RexValue v)
{
    RexValue* p = (RexValue*)malloc(sizeof(RexValue));
    if (!p) {
        rex_panic("rex: out of memory allocating a value box");
    }
    *p = v;
    return (W_)p;
}

/* Borrow the value inside a box.  Null boxes behave like `nil`. */
RexValue rex_cmm_val(W_ p)
{
    if (!p) {
        return rex_nil();
    }
    return *(RexValue*)p;
}

/* Borrow the C string inside a box; null/ non-string boxes yield "". */
const char* rex_cmm_cstr(W_ p)
{
    RexValue v = rex_cmm_val(p);
    if (v.tag != REX_STR || !v.as.str) {
        return "";
    }
    return v.as.str;
}

/* Pass a data-section string through unchanged.
 *
 * A NUL-separated blob (struct field names) cannot travel as a boxed Rex
 * string: `rex_str` copies with strlen, so every field name after the first
 * would be truncated away.  This hands the raw pointer straight through. */
const char* rex_cmm_cstr_raw(W_ p)
{
    return (const char*)p;
}

/* Raw pointer payload accessor, for `&x` style references. */
void* rex_cmm_addr(W_ p)
{
    return (void*)p;
}

W_ rex_cmm_num(double n);
W_ rex_cmm_str_raw(W_ s);
W_ rex_cmm_ptr(W_ p);
W_ rex_cmm_ref(W_ addr);
W_ rex_cmm_ref_mut(W_ addr);
W_ rex_cmm_struct_begin(void);
void rex_cmm_struct_push(W_ builder, W_ value);
W_ rex_cmm_struct_end(W_ builder, W_ name, W_ field_names);
W_ rex_cmm_struct_get(W_ obj, W_ field);
void rex_cmm_struct_set(W_ obj, W_ field, W_ value);
W_ rex_cmm_tuple_begin(void);
W_ rex_cmm_tuple_end(W_ builder);
W_ rex_cmm_vec_begin(void);
void rex_cmm_vec_push(W_ builder, W_ value);
W_ rex_cmm_vec_end(W_ builder);
void rex_cmm_os_set_args(int argc, char** argv);
W_ rex_cmm_spawn(W_ fn, W_ ctx);
W_ rex_cmm_stack_alloc(unsigned long bytes);
int rex_cmm_truthy_raw(W_ v);
int rex_cmm_tag_is_raw(W_ v, W_ tag);
int rex_cmm_result_is_raw(W_ v, W_ tag);

/* ---- generated wrappers ---- */


W_ rex_cmm_nil()
{
    return rex_cmm_mkbox(rex_nil());
}

W_ rex_cmm_bool(int b)
{
    return rex_cmm_mkbox(rex_bool(b));
}

W_ rex_cmm_str(W_ s)
{
    return rex_cmm_mkbox(rex_str(rex_cmm_cstr(s)));
}

void rex_cmm_drop(W_ v)
{
    rex_drop(rex_cmm_val(v));
}

W_ rex_cmm_is_truthy(W_ v)
{
    return rex_cmm_mkbox(rex_bool(rex_is_truthy(rex_cmm_val(v))));
}

W_ rex_cmm_add(W_ a, W_ b)
{
    return rex_cmm_mkbox(rex_add(rex_cmm_val(a), rex_cmm_val(b)));
}

W_ rex_cmm_sub(W_ a, W_ b)
{
    return rex_cmm_mkbox(rex_sub(rex_cmm_val(a), rex_cmm_val(b)));
}

W_ rex_cmm_mul(W_ a, W_ b)
{
    return rex_cmm_mkbox(rex_mul(rex_cmm_val(a), rex_cmm_val(b)));
}

W_ rex_cmm_div(W_ a, W_ b)
{
    return rex_cmm_mkbox(rex_div(rex_cmm_val(a), rex_cmm_val(b)));
}

W_ rex_cmm_mod(W_ a, W_ b)
{
    return rex_cmm_mkbox(rex_mod(rex_cmm_val(a), rex_cmm_val(b)));
}

W_ rex_cmm_eq(W_ a, W_ b)
{
    return rex_cmm_mkbox(rex_eq(rex_cmm_val(a), rex_cmm_val(b)));
}

W_ rex_cmm_neq(W_ a, W_ b)
{
    return rex_cmm_mkbox(rex_neq(rex_cmm_val(a), rex_cmm_val(b)));
}

W_ rex_cmm_lt(W_ a, W_ b)
{
    return rex_cmm_mkbox(rex_lt(rex_cmm_val(a), rex_cmm_val(b)));
}

W_ rex_cmm_lte(W_ a, W_ b)
{
    return rex_cmm_mkbox(rex_lte(rex_cmm_val(a), rex_cmm_val(b)));
}

W_ rex_cmm_gt(W_ a, W_ b)
{
    return rex_cmm_mkbox(rex_gt(rex_cmm_val(a), rex_cmm_val(b)));
}

W_ rex_cmm_gte(W_ a, W_ b)
{
    return rex_cmm_mkbox(rex_gte(rex_cmm_val(a), rex_cmm_val(b)));
}

W_ rex_cmm_neg(W_ v)
{
    return rex_cmm_mkbox(rex_neg(rex_cmm_val(v)));
}

W_ rex_cmm_not(W_ v)
{
    return rex_cmm_mkbox(rex_not(rex_cmm_val(v)));
}

W_ rex_cmm_and(W_ a, W_ b)
{
    return rex_cmm_mkbox(rex_and(rex_cmm_val(a), rex_cmm_val(b)));
}

W_ rex_cmm_or(W_ a, W_ b)
{
    return rex_cmm_mkbox(rex_or(rex_cmm_val(a), rex_cmm_val(b)));
}

void rex_cmm_println(W_ v)
{
    rex_println(rex_cmm_val(v));
}

void rex_cmm_print(W_ v)
{
    rex_print(rex_cmm_val(v));
}

W_ rex_cmm_ok(W_ v)
{
    return rex_cmm_mkbox(rex_ok(rex_cmm_val(v)));
}

W_ rex_cmm_err(W_ v)
{
    return rex_cmm_mkbox(rex_err(rex_cmm_val(v)));
}

W_ rex_cmm_result_is(W_ v, W_ tag)
{
    return rex_cmm_mkbox(rex_bool(rex_result_is(rex_cmm_val(v), rex_cmm_cstr(tag))));
}

W_ rex_cmm_result_value(W_ v)
{
    return rex_cmm_mkbox(rex_result_value(rex_cmm_val(v)));
}

W_ rex_cmm_tag(W_ tag, W_ v)
{
    return rex_cmm_mkbox(rex_tag(rex_cmm_cstr(tag), rex_cmm_val(v)));
}

W_ rex_cmm_tag_is(W_ v, W_ tag)
{
    return rex_cmm_mkbox(rex_bool(rex_tag_is(rex_cmm_val(v), rex_cmm_cstr(tag))));
}

W_ rex_cmm_tag_value(W_ v)
{
    return rex_cmm_mkbox(rex_tag_value(rex_cmm_val(v)));
}

W_ rex_cmm_try(W_ v)
{
    return rex_cmm_mkbox(rex_try(rex_cmm_val(v)));
}

W_ rex_cmm_alloc()
{
    return rex_cmm_mkbox(rex_alloc());
}

void rex_cmm_free(W_ p)
{
    rex_free(rex_cmm_val(p));
}

W_ rex_cmm_box(W_ v)
{
    return rex_cmm_mkbox(rex_box(rex_cmm_val(v)));
}

W_ rex_cmm_unbox(W_ p)
{
    return rex_cmm_mkbox(rex_unbox(rex_cmm_val(p)));
}

W_ rex_cmm_deref(W_ p)
{
    return rex_cmm_mkbox(rex_deref(rex_cmm_val(p)));
}

void rex_cmm_deref_assign(W_ p, W_ v)
{
    rex_deref_assign(rex_cmm_val(p), rex_cmm_val(v));
}

W_ rex_cmm_tuple_get(W_ tuple, int index)
{
    return rex_cmm_mkbox(rex_tuple_get(rex_cmm_val(tuple), index));
}

W_ rex_cmm_channel()
{
    return rex_cmm_mkbox(rex_channel());
}

void rex_cmm_sender_send(W_ sender, W_ value)
{
    rex_sender_send(rex_cmm_val(sender), rex_cmm_val(value));
}

W_ rex_cmm_receiver_recv(W_ receiver)
{
    return rex_cmm_mkbox(rex_receiver_recv(rex_cmm_val(receiver)));
}

W_ rex_cmm_wait_all()
{
    return rex_cmm_mkbox(rex_wait_all());
}

W_ rex_cmm_sleep(W_ ms)
{
    return rex_cmm_mkbox(rex_sleep(rex_cmm_val(ms)));
}

W_ rex_cmm_sleep_s(W_ seconds)
{
    return rex_cmm_mkbox(rex_sleep_s(rex_cmm_val(seconds)));
}

W_ rex_cmm_now_ms()
{
    return rex_cmm_mkbox(rex_now_ms());
}

W_ rex_cmm_now_s()
{
    return rex_cmm_mkbox(rex_now_s());
}

W_ rex_cmm_now_ns()
{
    return rex_cmm_mkbox(rex_now_ns());
}

W_ rex_cmm_time_since(W_ start)
{
    return rex_cmm_mkbox(rex_time_since(rex_cmm_val(start)));
}

W_ rex_cmm_format(W_ v)
{
    return rex_cmm_mkbox(rex_format(rex_cmm_val(v)));
}

W_ rex_cmm_fmt_pad_left(W_ value, W_ width, W_ fill)
{
    return rex_cmm_mkbox(rex_fmt_pad_left(rex_cmm_val(value), rex_cmm_val(width), rex_cmm_val(fill)));
}

W_ rex_cmm_fmt_pad_right(W_ value, W_ width, W_ fill)
{
    return rex_cmm_mkbox(rex_fmt_pad_right(rex_cmm_val(value), rex_cmm_val(width), rex_cmm_val(fill)));
}

W_ rex_cmm_fmt_join(W_ vec, W_ sep)
{
    return rex_cmm_mkbox(rex_fmt_join(rex_cmm_val(vec), rex_cmm_val(sep)));
}

W_ rex_cmm_fmt_fixed(W_ value, W_ digits)
{
    return rex_cmm_mkbox(rex_fmt_fixed(rex_cmm_val(value), rex_cmm_val(digits)));
}

W_ rex_cmm_fmt_hex(W_ value)
{
    return rex_cmm_mkbox(rex_fmt_hex(rex_cmm_val(value)));
}

W_ rex_cmm_fmt_bin(W_ value)
{
    return rex_cmm_mkbox(rex_fmt_bin(rex_cmm_val(value)));
}

W_ rex_cmm_sqrt(W_ v)
{
    return rex_cmm_mkbox(rex_sqrt(rex_cmm_val(v)));
}

W_ rex_cmm_abs(W_ v)
{
    return rex_cmm_mkbox(rex_abs(rex_cmm_val(v)));
}

W_ rex_cmm_math_eval(W_ expr)
{
    return rex_cmm_mkbox(rex_math_eval(rex_cmm_val(expr)));
}

W_ rex_cmm_text_initials(W_ text)
{
    return rex_cmm_mkbox(rex_text_initials(rex_cmm_val(text)));
}

W_ rex_cmm_text_lower_ascii(W_ text)
{
    return rex_cmm_mkbox(rex_text_lower_ascii(rex_cmm_val(text)));
}

W_ rex_cmm_text_pad_left(W_ text, W_ width, W_ fill)
{
    return rex_cmm_mkbox(rex_text_pad_left(rex_cmm_val(text), rex_cmm_val(width), rex_cmm_val(fill)));
}

W_ rex_cmm_text_pad_right(W_ text, W_ width, W_ fill)
{
    return rex_cmm_mkbox(rex_text_pad_right(rex_cmm_val(text), rex_cmm_val(width), rex_cmm_val(fill)));
}

W_ rex_cmm_text_trim(W_ text)
{
    return rex_cmm_mkbox(rex_text_trim(rex_cmm_val(text)));
}

W_ rex_cmm_text_trim_start(W_ text)
{
    return rex_cmm_mkbox(rex_text_trim_start(rex_cmm_val(text)));
}

W_ rex_cmm_text_trim_end(W_ text)
{
    return rex_cmm_mkbox(rex_text_trim_end(rex_cmm_val(text)));
}

W_ rex_cmm_text_split_words(W_ text)
{
    return rex_cmm_mkbox(rex_text_split_words(rex_cmm_val(text)));
}

W_ rex_cmm_text_starts_with(W_ text, W_ prefix)
{
    return rex_cmm_mkbox(rex_text_starts_with(rex_cmm_val(text), rex_cmm_val(prefix)));
}

W_ rex_cmm_text_ends_with(W_ text, W_ suffix)
{
    return rex_cmm_mkbox(rex_text_ends_with(rex_cmm_val(text), rex_cmm_val(suffix)));
}

W_ rex_cmm_text_contains(W_ text, W_ needle)
{
    return rex_cmm_mkbox(rex_text_contains(rex_cmm_val(text), rex_cmm_val(needle)));
}

W_ rex_cmm_text_replace(W_ text, W_ from, W_ to)
{
    return rex_cmm_mkbox(rex_text_replace(rex_cmm_val(text), rex_cmm_val(from), rex_cmm_val(to)));
}

W_ rex_cmm_text_repeat(W_ text, W_ count)
{
    return rex_cmm_mkbox(rex_text_repeat(rex_cmm_val(text), rex_cmm_val(count)));
}

W_ rex_cmm_text_lines(W_ text)
{
    return rex_cmm_mkbox(rex_text_lines(rex_cmm_val(text)));
}

W_ rex_cmm_text_upper_ascii(W_ text)
{
    return rex_cmm_mkbox(rex_text_upper_ascii(rex_cmm_val(text)));
}

W_ rex_cmm_text_is_empty(W_ text)
{
    return rex_cmm_mkbox(rex_text_is_empty(rex_cmm_val(text)));
}

W_ rex_cmm_text_len_bytes(W_ text)
{
    return rex_cmm_mkbox(rex_text_len_bytes(rex_cmm_val(text)));
}

W_ rex_cmm_text_index_of(W_ text, W_ needle)
{
    return rex_cmm_mkbox(rex_text_index_of(rex_cmm_val(text), rex_cmm_val(needle)));
}

W_ rex_cmm_text_last_index_of(W_ text, W_ needle)
{
    return rex_cmm_mkbox(rex_text_last_index_of(rex_cmm_val(text), rex_cmm_val(needle)));
}

W_ rex_cmm_io_read_file(W_ path)
{
    return rex_cmm_mkbox(rex_io_read_file(rex_cmm_val(path)));
}

W_ rex_cmm_io_write_file(W_ path, W_ data)
{
    return rex_cmm_mkbox(rex_io_write_file(rex_cmm_val(path), rex_cmm_val(data)));
}

W_ rex_cmm_io_read_line()
{
    return rex_cmm_mkbox(rex_io_read_line());
}

W_ rex_cmm_io_read_lines(W_ path)
{
    return rex_cmm_mkbox(rex_io_read_lines(rex_cmm_val(path)));
}

W_ rex_cmm_io_write_lines(W_ path, W_ lines)
{
    return rex_cmm_mkbox(rex_io_write_lines(rex_cmm_val(path), rex_cmm_val(lines)));
}

W_ rex_cmm_fs_exists(W_ path)
{
    return rex_cmm_mkbox(rex_fs_exists(rex_cmm_val(path)));
}

W_ rex_cmm_fs_mkdir(W_ path)
{
    return rex_cmm_mkbox(rex_fs_mkdir(rex_cmm_val(path)));
}

W_ rex_cmm_fs_remove(W_ path)
{
    return rex_cmm_mkbox(rex_fs_remove(rex_cmm_val(path)));
}

W_ rex_cmm_fs_is_dir(W_ path)
{
    return rex_cmm_mkbox(rex_fs_is_dir(rex_cmm_val(path)));
}

W_ rex_cmm_fs_read_dir(W_ path)
{
    return rex_cmm_mkbox(rex_fs_read_dir(rex_cmm_val(path)));
}

W_ rex_cmm_fs_copy(W_ src, W_ dst)
{
    return rex_cmm_mkbox(rex_fs_copy(rex_cmm_val(src), rex_cmm_val(dst)));
}

W_ rex_cmm_fs_move(W_ src, W_ dst)
{
    return rex_cmm_mkbox(rex_fs_move(rex_cmm_val(src), rex_cmm_val(dst)));
}

W_ rex_cmm_os_getenv(W_ key)
{
    return rex_cmm_mkbox(rex_os_getenv(rex_cmm_val(key)));
}

W_ rex_cmm_os_cwd()
{
    return rex_cmm_mkbox(rex_os_cwd());
}

W_ rex_cmm_os_platform()
{
    return rex_cmm_mkbox(rex_os_platform());
}

W_ rex_cmm_os_args()
{
    return rex_cmm_mkbox(rex_os_args());
}

W_ rex_cmm_os_home()
{
    return rex_cmm_mkbox(rex_os_home());
}

W_ rex_cmm_os_temp_dir()
{
    return rex_cmm_mkbox(rex_os_temp_dir());
}

W_ rex_cmm_path_join(W_ a, W_ b)
{
    return rex_cmm_mkbox(rex_path_join(rex_cmm_val(a), rex_cmm_val(b)));
}

W_ rex_cmm_path_basename(W_ path)
{
    return rex_cmm_mkbox(rex_path_basename(rex_cmm_val(path)));
}

W_ rex_cmm_path_dirname(W_ path)
{
    return rex_cmm_mkbox(rex_path_dirname(rex_cmm_val(path)));
}

W_ rex_cmm_path_ext(W_ path)
{
    return rex_cmm_mkbox(rex_path_ext(rex_cmm_val(path)));
}

W_ rex_cmm_path_stem(W_ path)
{
    return rex_cmm_mkbox(rex_path_stem(rex_cmm_val(path)));
}

W_ rex_cmm_path_is_abs(W_ path)
{
    return rex_cmm_mkbox(rex_path_is_abs(rex_cmm_val(path)));
}

W_ rex_cmm_audio_play(W_ path)
{
    return rex_cmm_mkbox(rex_audio_play(rex_cmm_val(path)));
}

W_ rex_cmm_audio_play_loop(W_ path)
{
    return rex_cmm_mkbox(rex_audio_play_loop(rex_cmm_val(path)));
}

W_ rex_cmm_audio_stop()
{
    return rex_cmm_mkbox(rex_audio_stop());
}

W_ rex_cmm_audio_supports(W_ ext)
{
    return rex_cmm_mkbox(rex_audio_supports(rex_cmm_val(ext)));
}

W_ rex_cmm_audio_set_volume(W_ value)
{
    return rex_cmm_mkbox(rex_audio_set_volume(rex_cmm_val(value)));
}

W_ rex_cmm_audio_get_volume()
{
    return rex_cmm_mkbox(rex_audio_get_volume());
}

W_ rex_cmm_log_debug(W_ value)
{
    return rex_cmm_mkbox(rex_log_debug(rex_cmm_val(value)));
}

W_ rex_cmm_log_info(W_ value)
{
    return rex_cmm_mkbox(rex_log_info(rex_cmm_val(value)));
}

W_ rex_cmm_log_warn(W_ value)
{
    return rex_cmm_mkbox(rex_log_warn(rex_cmm_val(value)));
}

W_ rex_cmm_log_error(W_ value)
{
    return rex_cmm_mkbox(rex_log_error(rex_cmm_val(value)));
}

W_ rex_cmm_log_set_level(W_ value)
{
    return rex_cmm_mkbox(rex_log_set_level(rex_cmm_val(value)));
}

W_ rex_cmm_log_get_level()
{
    return rex_cmm_mkbox(rex_log_get_level());
}

W_ rex_cmm_collections_vec_new()
{
    return rex_cmm_mkbox(rex_collections_vec_new());
}

void rex_cmm_collections_vec_push(W_ vec, W_ value)
{
    rex_collections_vec_push(rex_cmm_val(vec), rex_cmm_val(value));
}

W_ rex_cmm_collections_vec_get(W_ vec, W_ index)
{
    return rex_cmm_mkbox(rex_collections_vec_get(rex_cmm_val(vec), rex_cmm_val(index)));
}

void rex_cmm_collections_vec_set(W_ vec, W_ index, W_ value)
{
    rex_collections_vec_set(rex_cmm_val(vec), rex_cmm_val(index), rex_cmm_val(value));
}

W_ rex_cmm_collections_vec_len(W_ vec)
{
    return rex_cmm_mkbox(rex_collections_vec_len(rex_cmm_val(vec)));
}

W_ rex_cmm_collections_vec_insert(W_ vec, W_ index, W_ value)
{
    return rex_cmm_mkbox(rex_collections_vec_insert(rex_cmm_val(vec), rex_cmm_val(index), rex_cmm_val(value)));
}

W_ rex_cmm_collections_vec_slice(W_ vec, W_ start, W_ finish)
{
    return rex_cmm_mkbox(rex_collections_vec_slice(rex_cmm_val(vec), rex_cmm_val(start), rex_cmm_val(finish)));
}

W_ rex_cmm_collections_vec_pop(W_ vec)
{
    return rex_cmm_mkbox(rex_collections_vec_pop(rex_cmm_val(vec)));
}

W_ rex_cmm_collections_vec_clear(W_ vec)
{
    return rex_cmm_mkbox(rex_collections_vec_clear(rex_cmm_val(vec)));
}

W_ rex_cmm_collections_vec_sort(W_ vec)
{
    return rex_cmm_mkbox(rex_collections_vec_sort(rex_cmm_val(vec)));
}

W_ rex_cmm_collections_vec_find(W_ vec, W_ value)
{
    return rex_cmm_mkbox(rex_collections_vec_find(rex_cmm_val(vec), rex_cmm_val(value)));
}

W_ rex_cmm_collections_vec_any(W_ vec, W_ value)
{
    return rex_cmm_mkbox(rex_collections_vec_any(rex_cmm_val(vec), rex_cmm_val(value)));
}

W_ rex_cmm_collections_vec_all(W_ vec, W_ value)
{
    return rex_cmm_mkbox(rex_collections_vec_all(rex_cmm_val(vec), rex_cmm_val(value)));
}

W_ rex_cmm_collections_vec_contains(W_ vec, W_ value)
{
    return rex_cmm_mkbox(rex_collections_vec_contains(rex_cmm_val(vec), rex_cmm_val(value)));
}

W_ rex_cmm_collections_vec_remove_at(W_ vec, W_ index)
{
    return rex_cmm_mkbox(rex_collections_vec_remove_at(rex_cmm_val(vec), rex_cmm_val(index)));
}

W_ rex_cmm_collections_vec_reverse(W_ vec)
{
    return rex_cmm_mkbox(rex_collections_vec_reverse(rex_cmm_val(vec)));
}

W_ rex_cmm_collections_vec_first(W_ vec)
{
    return rex_cmm_mkbox(rex_collections_vec_first(rex_cmm_val(vec)));
}

W_ rex_cmm_collections_vec_last(W_ vec)
{
    return rex_cmm_mkbox(rex_collections_vec_last(rex_cmm_val(vec)));
}

W_ rex_cmm_collections_vec_join(W_ vec, W_ sep)
{
    return rex_cmm_mkbox(rex_collections_vec_join(rex_cmm_val(vec), rex_cmm_val(sep)));
}

W_ rex_cmm_collections_get(W_ object, W_ index)
{
    return rex_cmm_mkbox(rex_collections_get(rex_cmm_val(object), rex_cmm_val(index)));
}

W_ rex_cmm_collections_slice(W_ object, W_ start, W_ finish)
{
    return rex_cmm_mkbox(rex_collections_slice(rex_cmm_val(object), rex_cmm_val(start), rex_cmm_val(finish)));
}

void rex_cmm_collections_set(W_ object, W_ index, W_ value)
{
    rex_collections_set(rex_cmm_val(object), rex_cmm_val(index), rex_cmm_val(value));
}

W_ rex_cmm_collections_map_new()
{
    return rex_cmm_mkbox(rex_collections_map_new());
}

void rex_cmm_collections_map_put(W_ map, W_ key, W_ value)
{
    rex_collections_map_put(rex_cmm_val(map), rex_cmm_val(key), rex_cmm_val(value));
}

W_ rex_cmm_collections_map_get(W_ map, W_ key)
{
    return rex_cmm_mkbox(rex_collections_map_get(rex_cmm_val(map), rex_cmm_val(key)));
}

W_ rex_cmm_collections_map_remove(W_ map, W_ key)
{
    return rex_cmm_mkbox(rex_collections_map_remove(rex_cmm_val(map), rex_cmm_val(key)));
}

W_ rex_cmm_collections_map_has(W_ map, W_ key)
{
    return rex_cmm_mkbox(rex_collections_map_has(rex_cmm_val(map), rex_cmm_val(key)));
}

W_ rex_cmm_collections_map_keys(W_ map)
{
    return rex_cmm_mkbox(rex_collections_map_keys(rex_cmm_val(map)));
}

W_ rex_cmm_collections_map_values(W_ map)
{
    return rex_cmm_mkbox(rex_collections_map_values(rex_cmm_val(map)));
}

W_ rex_cmm_collections_map_items(W_ map)
{
    return rex_cmm_mkbox(rex_collections_map_items(rex_cmm_val(map)));
}

W_ rex_cmm_collections_map_len(W_ map)
{
    return rex_cmm_mkbox(rex_collections_map_len(rex_cmm_val(map)));
}

W_ rex_cmm_collections_set_new()
{
    return rex_cmm_mkbox(rex_collections_set_new());
}

void rex_cmm_collections_set_add(W_ set, W_ value)
{
    rex_collections_set_add(rex_cmm_val(set), rex_cmm_val(value));
}

W_ rex_cmm_collections_set_has(W_ set, W_ value)
{
    return rex_cmm_mkbox(rex_collections_set_has(rex_cmm_val(set), rex_cmm_val(value)));
}

W_ rex_cmm_collections_set_remove(W_ set, W_ value)
{
    return rex_cmm_mkbox(rex_collections_set_remove(rex_cmm_val(set), rex_cmm_val(value)));
}

W_ rex_cmm_collections_set_len(W_ set)
{
    return rex_cmm_mkbox(rex_collections_set_len(rex_cmm_val(set)));
}

W_ rex_cmm_result_is_ok(W_ value)
{
    return rex_cmm_mkbox(rex_result_is_ok(rex_cmm_val(value)));
}

W_ rex_cmm_result_is_err(W_ value)
{
    return rex_cmm_mkbox(rex_result_is_err(rex_cmm_val(value)));
}

W_ rex_cmm_result_unwrap_or(W_ value, W_ fallback)
{
    return rex_cmm_mkbox(rex_result_unwrap_or(rex_cmm_val(value), rex_cmm_val(fallback)));
}

W_ rex_cmm_result_unwrap_or_else(W_ value, W_ fallback)
{
    return rex_cmm_mkbox(rex_result_unwrap_or_else(rex_cmm_val(value), rex_cmm_val(fallback)));
}

W_ rex_cmm_result_ok_or(W_ value, W_ err)
{
    return rex_cmm_mkbox(rex_result_ok_or(rex_cmm_val(value), rex_cmm_val(err)));
}

W_ rex_cmm_result_expect(W_ value, W_ message)
{
    return rex_cmm_mkbox(rex_result_expect(rex_cmm_val(value), rex_cmm_val(message)));
}

W_ rex_cmm_net_tcp_connect(W_ addr)
{
    return rex_cmm_mkbox(rex_net_tcp_connect(rex_cmm_val(addr)));
}

W_ rex_cmm_net_udp_socket()
{
    return rex_cmm_mkbox(rex_net_udp_socket());
}

W_ rex_cmm_http_get(W_ url)
{
    return rex_cmm_mkbox(rex_http_get(rex_cmm_val(url)));
}

W_ rex_cmm_http_get_status(W_ url)
{
    return rex_cmm_mkbox(rex_http_get_status(rex_cmm_val(url)));
}

W_ rex_cmm_http_get_json(W_ url)
{
    return rex_cmm_mkbox(rex_http_get_json(rex_cmm_val(url)));
}

W_ rex_cmm_process_run(W_ command)
{
    return rex_cmm_mkbox(rex_process_run(rex_cmm_val(command)));
}

W_ rex_cmm_process_capture(W_ command)
{
    return rex_cmm_mkbox(rex_process_capture(rex_cmm_val(command)));
}

W_ rex_cmm_url_parse(W_ url)
{
    return rex_cmm_mkbox(rex_url_parse(rex_cmm_val(url)));
}

W_ rex_cmm_url_encode_component(W_ text)
{
    return rex_cmm_mkbox(rex_url_encode_component(rex_cmm_val(text)));
}

W_ rex_cmm_url_decode_component(W_ text)
{
    return rex_cmm_mkbox(rex_url_decode_component(rex_cmm_val(text)));
}

W_ rex_cmm_url_join(W_ base, W_ part)
{
    return rex_cmm_mkbox(rex_url_join(rex_cmm_val(base), rex_cmm_val(part)));
}

W_ rex_cmm_url_with_query(W_ base, W_ params)
{
    return rex_cmm_mkbox(rex_url_with_query(rex_cmm_val(base), rex_cmm_val(params)));
}

W_ rex_cmm_random_seed(W_ seed)
{
    return rex_cmm_mkbox(rex_random_seed(rex_cmm_val(seed)));
}

W_ rex_cmm_random_int(W_ min, W_ max)
{
    return rex_cmm_mkbox(rex_random_int(rex_cmm_val(min), rex_cmm_val(max)));
}

W_ rex_cmm_random_float()
{
    return rex_cmm_mkbox(rex_random_float());
}

W_ rex_cmm_random_bool(W_ probability)
{
    return rex_cmm_mkbox(rex_random_bool(rex_cmm_val(probability)));
}

W_ rex_cmm_random_choice(W_ vec)
{
    return rex_cmm_mkbox(rex_random_choice(rex_cmm_val(vec)));
}

W_ rex_cmm_random_shuffle(W_ vec)
{
    return rex_cmm_mkbox(rex_random_shuffle(rex_cmm_val(vec)));
}

W_ rex_cmm_random_range(W_ min, W_ max)
{
    return rex_cmm_mkbox(rex_random_range(rex_cmm_val(min), rex_cmm_val(max)));
}

W_ rex_cmm_json_encode(W_ v)
{
    return rex_cmm_mkbox(rex_json_encode(rex_cmm_val(v)));
}

W_ rex_cmm_json_encode_pretty(W_ v, W_ indent)
{
    return rex_cmm_mkbox(rex_json_encode_pretty(rex_cmm_val(v), rex_cmm_val(indent)));
}

W_ rex_cmm_json_decode(W_ s)
{
    return rex_cmm_mkbox(rex_json_decode(rex_cmm_val(s)));
}

W_ rex_cmm_ui_begin(W_ title, W_ width, W_ height)
{
    return rex_cmm_mkbox(rex_ui_begin(rex_cmm_val(title), rex_cmm_val(width), rex_cmm_val(height)));
}

W_ rex_cmm_ui_end()
{
    return rex_cmm_mkbox(rex_ui_end());
}

W_ rex_cmm_ui_redraw()
{
    return rex_cmm_mkbox(rex_ui_redraw());
}

W_ rex_cmm_ui_clear(W_ color)
{
    return rex_cmm_mkbox(rex_ui_clear(rex_cmm_val(color)));
}

W_ rex_cmm_ui_key_space()
{
    return rex_cmm_mkbox(rex_ui_key_space());
}

W_ rex_cmm_ui_key_up()
{
    return rex_cmm_mkbox(rex_ui_key_up());
}

W_ rex_cmm_ui_key_down()
{
    return rex_cmm_mkbox(rex_ui_key_down());
}

W_ rex_cmm_ui_key_code(W_ name)
{
    return rex_cmm_mkbox(rex_ui_key_code(rex_cmm_val(name)));
}

W_ rex_cmm_ui_key_is_down(W_ key)
{
    return rex_cmm_mkbox(rex_ui_key_is_down(rex_cmm_val(key)));
}

W_ rex_cmm_ui_key_pressed(W_ key)
{
    return rex_cmm_mkbox(rex_ui_key_pressed(rex_cmm_val(key)));
}

W_ rex_cmm_ui_key_released(W_ key)
{
    return rex_cmm_mkbox(rex_ui_key_released(rex_cmm_val(key)));
}

W_ rex_cmm_ui_mouse_x()
{
    return rex_cmm_mkbox(rex_ui_mouse_x());
}

W_ rex_cmm_ui_mouse_y()
{
    return rex_cmm_mkbox(rex_ui_mouse_y());
}

W_ rex_cmm_ui_mouse_down()
{
    return rex_cmm_mkbox(rex_ui_mouse_down());
}

W_ rex_cmm_ui_mouse_pressed()
{
    return rex_cmm_mkbox(rex_ui_mouse_pressed());
}

W_ rex_cmm_ui_mouse_released()
{
    return rex_cmm_mkbox(rex_ui_mouse_released());
}

W_ rex_cmm_ui_mouse_is_down(W_ button)
{
    return rex_cmm_mkbox(rex_ui_mouse_is_down(rex_cmm_val(button)));
}

W_ rex_cmm_ui_mouse_pressed_btn(W_ button)
{
    return rex_cmm_mkbox(rex_ui_mouse_pressed_btn(rex_cmm_val(button)));
}

W_ rex_cmm_ui_mouse_released_btn(W_ button)
{
    return rex_cmm_mkbox(rex_ui_mouse_released_btn(rex_cmm_val(button)));
}

W_ rex_cmm_ui_scroll_x()
{
    return rex_cmm_mkbox(rex_ui_scroll_x());
}

W_ rex_cmm_ui_scroll_y()
{
    return rex_cmm_mkbox(rex_ui_scroll_y());
}

W_ rex_cmm_ui_label(W_ text)
{
    return rex_cmm_mkbox(rex_ui_label(rex_cmm_val(text)));
}

W_ rex_cmm_ui_text(W_ x, W_ y, W_ text, W_ color)
{
    return rex_cmm_mkbox(rex_ui_text(rex_cmm_val(x), rex_cmm_val(y), rex_cmm_val(text), rex_cmm_val(color)));
}

W_ rex_cmm_ui_rect(W_ x, W_ y, W_ w, W_ h, W_ color)
{
    return rex_cmm_mkbox(rex_ui_rect(rex_cmm_val(x), rex_cmm_val(y), rex_cmm_val(w), rex_cmm_val(h), rex_cmm_val(color)));
}

W_ rex_cmm_ui_button(W_ label)
{
    return rex_cmm_mkbox(rex_ui_button(rex_cmm_val(label)));
}

W_ rex_cmm_ui_checkbox(W_ label, W_ checked)
{
    return rex_cmm_mkbox(rex_ui_checkbox(rex_cmm_val(label), rex_cmm_val(checked)));
}

W_ rex_cmm_ui_radio(W_ label, W_ active)
{
    return rex_cmm_mkbox(rex_ui_radio(rex_cmm_val(label), rex_cmm_val(active)));
}

W_ rex_cmm_ui_textbox(W_ value, W_ width)
{
    return rex_cmm_mkbox(rex_ui_textbox(rex_cmm_val(value), rex_cmm_val(width)));
}

W_ rex_cmm_ui_slider(W_ label, W_ value, W_ min, W_ max)
{
    return rex_cmm_mkbox(rex_ui_slider(rex_cmm_val(label), rex_cmm_val(value), rex_cmm_val(min), rex_cmm_val(max)));
}

W_ rex_cmm_ui_progress(W_ value, W_ max)
{
    return rex_cmm_mkbox(rex_ui_progress(rex_cmm_val(value), rex_cmm_val(max)));
}

W_ rex_cmm_ui_switch(W_ label, W_ active)
{
    return rex_cmm_mkbox(rex_ui_switch(rex_cmm_val(label), rex_cmm_val(active)));
}

W_ rex_cmm_ui_select(W_ items, W_ selected)
{
    return rex_cmm_mkbox(rex_ui_select(rex_cmm_val(items), rex_cmm_val(selected)));
}

W_ rex_cmm_ui_combo(W_ items, W_ selected)
{
    return rex_cmm_mkbox(rex_ui_combo(rex_cmm_val(items), rex_cmm_val(selected)));
}

W_ rex_cmm_ui_menu(W_ items, W_ selected)
{
    return rex_cmm_mkbox(rex_ui_menu(rex_cmm_val(items), rex_cmm_val(selected)));
}

W_ rex_cmm_ui_tabs(W_ items, W_ selected)
{
    return rex_cmm_mkbox(rex_ui_tabs(rex_cmm_val(items), rex_cmm_val(selected)));
}

W_ rex_cmm_ui_layout_row(W_ height)
{
    return rex_cmm_mkbox(rex_ui_layout_row(rex_cmm_val(height)));
}

W_ rex_cmm_ui_layout_column(W_ height)
{
    return rex_cmm_mkbox(rex_ui_layout_column(rex_cmm_val(height)));
}

W_ rex_cmm_ui_layout_grid(W_ cols, W_ cell_w, W_ cell_h)
{
    return rex_cmm_mkbox(rex_ui_layout_grid(rex_cmm_val(cols), rex_cmm_val(cell_w), rex_cmm_val(cell_h)));
}

W_ rex_cmm_ui_newline()
{
    return rex_cmm_mkbox(rex_ui_newline());
}

W_ rex_cmm_ui_row_end()
{
    return rex_cmm_mkbox(rex_ui_row_end());
}

W_ rex_cmm_ui_clip_begin(W_ x, W_ y, W_ w, W_ h)
{
    return rex_cmm_mkbox(rex_ui_clip_begin(rex_cmm_val(x), rex_cmm_val(y), rex_cmm_val(w), rex_cmm_val(h)));
}

W_ rex_cmm_ui_clip_end()
{
    return rex_cmm_mkbox(rex_ui_clip_end());
}

W_ rex_cmm_ui_spacing(W_ px)
{
    return rex_cmm_mkbox(rex_ui_spacing(rex_cmm_val(px)));
}

W_ rex_cmm_ui_padding(W_ px)
{
    return rex_cmm_mkbox(rex_ui_padding(rex_cmm_val(px)));
}

W_ rex_cmm_ui_scroll_begin(W_ height)
{
    return rex_cmm_mkbox(rex_ui_scroll_begin(rex_cmm_val(height)));
}

W_ rex_cmm_ui_scroll_end()
{
    return rex_cmm_mkbox(rex_ui_scroll_end());
}

W_ rex_cmm_ui_enabled(W_ enabled)
{
    return rex_cmm_mkbox(rex_ui_enabled(rex_cmm_val(enabled)));
}

W_ rex_cmm_ui_invert(W_ enabled)
{
    return rex_cmm_mkbox(rex_ui_invert(rex_cmm_val(enabled)));
}

W_ rex_cmm_ui_titlebar_dark(W_ enabled)
{
    return rex_cmm_mkbox(rex_ui_titlebar_dark(rex_cmm_val(enabled)));
}

W_ rex_cmm_ui_theme_dark()
{
    return rex_cmm_mkbox(rex_ui_theme_dark());
}

W_ rex_cmm_ui_theme_light()
{
    return rex_cmm_mkbox(rex_ui_theme_light());
}

W_ rex_cmm_ui_theme_custom(W_ bg, W_ panel, W_ text, W_ muted, W_ button, W_ button_hover, W_ button_active, W_ accent, W_ select)
{
    return rex_cmm_mkbox(rex_ui_theme_custom(rex_cmm_val(bg), rex_cmm_val(panel), rex_cmm_val(text), rex_cmm_val(muted), rex_cmm_val(button), rex_cmm_val(button_hover), rex_cmm_val(button_active), rex_cmm_val(accent), rex_cmm_val(select)));
}

W_ rex_cmm_ui_image_load(W_ path)
{
    return rex_cmm_mkbox(rex_ui_image_load(rex_cmm_val(path)));
}

W_ rex_cmm_ui_image_w(W_ img)
{
    return rex_cmm_mkbox(rex_ui_image_w(rex_cmm_val(img)));
}

W_ rex_cmm_ui_image_h(W_ img)
{
    return rex_cmm_mkbox(rex_ui_image_h(rex_cmm_val(img)));
}

W_ rex_cmm_ui_image(W_ img, W_ x, W_ y)
{
    return rex_cmm_mkbox(rex_ui_image(rex_cmm_val(img), rex_cmm_val(x), rex_cmm_val(y)));
}

W_ rex_cmm_ui_image_rot(W_ img, W_ x, W_ y, W_ angle_deg)
{
    return rex_cmm_mkbox(rex_ui_image_rot(rex_cmm_val(img), rex_cmm_val(x), rex_cmm_val(y), rex_cmm_val(angle_deg)));
}

W_ rex_cmm_ui_image_region(W_ img, W_ sx, W_ sy, W_ sw, W_ sh, W_ x, W_ y, W_ w, W_ h)
{
    return rex_cmm_mkbox(rex_ui_image_region(rex_cmm_val(img), rex_cmm_val(sx), rex_cmm_val(sy), rex_cmm_val(sw), rex_cmm_val(sh), rex_cmm_val(x), rex_cmm_val(y), rex_cmm_val(w), rex_cmm_val(h)));
}

W_ rex_cmm_ui_play_sound(W_ path)
{
    return rex_cmm_mkbox(rex_ui_play_sound(rex_cmm_val(path)));
}

void rex_cmm_panic(W_ msg)
{
    rex_panic(rex_cmm_cstr(msg));
}

void rex_cmm_ownership_debug_enable()
{
    rex_ownership_debug_enable();
}

void rex_cmm_ownership_debug_disable()
{
    rex_ownership_debug_disable();
}

void rex_cmm_ownership_trace(W_ variable, W_ event)
{
    rex_ownership_trace(rex_cmm_cstr(variable), rex_cmm_cstr(event));
}

void rex_cmm_ownership_check(W_ variable)
{
    rex_ownership_check(rex_cmm_cstr(variable));
}

void rex_cmm_ownership_cleanup()
{
    rex_ownership_cleanup();
}

W_ rex_cmm_temporal_now_ms()
{
    return rex_cmm_mkbox(rex_num((double)rex_temporal_now_ms()));
}

W_ rex_cmm_temporal_is_expired(uint64_t start_time, uint64_t lifetime_ms)
{
    return rex_cmm_mkbox(rex_bool(rex_temporal_is_expired(start_time, lifetime_ms)));
}


/* ---- hand-written wrappers ---- */


W_ rex_cmm_vec_begin(void)
{
    return rex_cmm_struct_begin();
}

void rex_cmm_vec_push(W_ builder, W_ value)
{
    rex_cmm_struct_push(builder, value);
}

W_ rex_cmm_vec_end(W_ builder)
{
    W_* b = (W_*)builder;
    RexValue* values = (RexValue*)((W_*)b)[0];
    size_t count = (size_t)((W_*)b)[1];
    W_ result = rex_cmm_mkbox(rex_collections_vec_from((int)count, values));
    free(values);
    free(builder);
    return result;
}


/* Cmm can pass a real `double` as a foreign argument (only *returns* are
 * broken), so numeric literals are built here from a genuine double. */
W_ rex_cmm_num(double n)
{
    return rex_cmm_mkbox(rex_num(n));
}


/* argv is captured by the generated Cmm entry point, which receives the
 * process arguments through the C main wrapper. */
void rex_cmm_os_set_args(int argc, char** argv)
{
    rex_os_set_args(argc, argv);
}


W_ rex_cmm_ptr(W_ p)
{
    return rex_cmm_mkbox(rex_ptr(p));
}


/* A reference is a box that points at another box. */
W_ rex_cmm_ref(W_ addr)
{
    return rex_cmm_mkbox(rex_ref((RexValue*)addr));
}


W_ rex_cmm_ref_mut(W_ addr)
{
    return rex_cmm_mkbox(rex_ref_mut((RexValue*)addr));
}


/* NOT SUPPORTED YET.
 *
 * `rex_spawn` takes a C function pointer and invokes it on a new OS thread.
 * gmm compiles Cmm functions to the GHC register convention (R1 = rax), not
 * the C ABI (first argument in rdi), so a Cmm label cannot be called back
 * from C.  A trampoline would also have to install a fresh `Sp`/`SpLim` on
 * the new thread, because `Sp` is a machine register and starts out
 * garbage there.  Until both are solved this fails loudly instead of
 * silently misbehaving. */
W_ rex_cmm_spawn(W_ fn, W_ ctx)
{
    (void)fn;
    (void)ctx;
    rex_panic("rex: the Cmm target does not support spawn yet");
    return NULL;
}


/* Build a Rex string from a *raw* C string literal in the Cmm data
 * section.  The generic `rex_cmm_str` wrapper takes an already-boxed Rex
 * string, so string literals need this separate raw entry point. */
W_ rex_cmm_str_raw(W_ s)
{
    return rex_cmm_mkbox(rex_str((const char*)s));
}


W_ rex_cmm_struct_get(W_ obj, W_ field)
{
    return rex_cmm_mkbox(rex_struct_get(rex_cmm_val(obj), rex_cmm_cstr(field)));
}


/* Struct construction is exposed as a builder because the C entry point
 * takes a `const char**` field-name table that cannot be built conveniently
 * from Cmm.  The generated code pushes one boxed value per field and then
 * calls rex_cmm_struct_end with a NUL-separated field-name blob. */
W_ rex_cmm_struct_begin(void)
{
    RexValue* values = NULL;
    size_t count = 0;
    size_t cap = 0;
    W_ b = malloc(sizeof(void*) * 3);
    if (!b) {
        rex_panic("rex: out of memory building a struct");
    }
    ((W_*)b)[0] = (W_)values;
    ((W_*)b)[1] = (W_)count;
    ((W_*)b)[2] = (W_)cap;
    return b;
}

void rex_cmm_struct_push(W_ builder, W_ value)
{
    W_* b = (W_*)builder;
    RexValue* values = (RexValue*)((W_*)b)[0];
    size_t count = (size_t)((W_*)b)[1];
    size_t cap = (size_t)((W_*)b)[2];
    if (count == cap) {
        size_t next = cap ? cap * 2 : 8;
        RexValue* grown = (RexValue*)realloc(values, next * sizeof(RexValue));
        if (!grown) {
            rex_panic("rex: out of memory building a struct");
        }
        values = grown;
        ((W_*)b)[0] = (W_)values;
        ((W_*)b)[2] = (W_)next;
    }
    values[count] = rex_cmm_val(value);
    ((W_*)b)[1] = (W_)(count + 1);
}

W_ rex_cmm_struct_end(W_ builder, W_ name, W_ field_names)
{
    W_* b = (W_*)builder;
    RexValue* values = (RexValue*)((W_*)b)[0];
    size_t count = (size_t)((W_*)b)[1];
    const char* blob = rex_cmm_cstr_raw(field_names);
    const char* cursor = blob;
    const char** names = NULL;
    size_t i;
    W_ result;
    if (count) {
        names = (const char**)malloc(count * sizeof(char*));
        if (!names) {
            rex_panic("rex: out of memory building a struct");
        }
        for (i = 0; i < count; i++) {
            names[i] = cursor;
            cursor += strlen(cursor) + 1;
        }
    }
    result = rex_cmm_mkbox(rex_struct_new(rex_cmm_cstr(name), names, values, (int)count));
    /* `rex_struct_new` stores the field-name table by reference rather than
     * copying it, and `s->fields` stays live for the struct's whole lifetime.
     * Freeing it here would leave every later `rex_struct_get`/`set` reading
     * freed memory, so the table is intentionally retained. */
    free(values);
    free(builder);
    return result;
}


void rex_cmm_struct_set(W_ obj, W_ field, W_ value)
{
    rex_struct_set(rex_cmm_val(obj), rex_cmm_cstr(field), rex_cmm_val(value));
}


/* Same builder shape as structs, for `rex_tuple_new`. */
W_ rex_cmm_tuple_begin(void)
{
    W_ b = rex_cmm_struct_begin();
    return b;
}

W_ rex_cmm_tuple_end(W_ builder)
{
    W_* b = (W_*)builder;
    RexValue* values = (RexValue*)((W_*)b)[0];
    size_t count = (size_t)((W_*)b)[1];
    W_ result = rex_cmm_mkbox(rex_tuple_new((int)count, values));
    free(values);
    free(builder);
    return result;
}


/* ---- runtime support ---- */

/* The Cmm backend needs a real machine stack: gmm's `return` writes through
 * Sp, and a standalone Cmm program starts with Sp pointing nowhere.  The
 * generated entry point calls this to obtain one, then sets
 * `Sp = base + size; SpLim = base;`. */
W_ rex_cmm_stack_alloc(unsigned long bytes)
{
    void* p = malloc(bytes);
    if (!p) {
        rex_panic("rex: could not allocate the Cmm stack");
    }
    return (W_)p;
}

/* Raw (unboxed) predicates.
 *
 * Every other wrapper returns a W_ box, but Cmm control flow wants a plain
 * machine integer it can test with `if (n != 0)`.  Foreign `int` returns do
 * work in gmm, so these expose the underlying C ints directly. */
int rex_cmm_truthy_raw(W_ v)
{
    return rex_is_truthy(rex_cmm_val(v));
}

int rex_cmm_tag_is_raw(W_ v, W_ tag)
{
    return rex_tag_is(rex_cmm_val(v), rex_cmm_cstr(tag)) ? 1 : 0;
}

int rex_cmm_result_is_raw(W_ v, W_ tag)
{
    return rex_result_is(rex_cmm_val(v), rex_cmm_cstr(tag)) ? 1 : 0;
}
