local schema = {
  Program = { required = { "items" } },
  Use = { required = { "path" }, optional = { "alias" } },
  Struct = { required = { "name", "fields" }, optional = { "params", "param_bounds", "public" } },
  TypeAlias = { required = { "name", "aliased" }, optional = { "public" } },
  Enum = { required = { "name", "variants" }, optional = { "params", "param_bounds", "public" } },
  Impl = { required = { "name", "methods" }, optional = { "params", "param_bounds", "public" } },
  Function = {
    required = { "name", "params", "body" },
    optional = { "return_type", "type_params", "type_param_bounds", "is_method", "public" },
  },

  Block = { required = { "statements" } },
  Let = { required = { "mutable", "pattern", "value" }, optional = { "type" } },
  Bond = { required = { "name", "value" } },
  Commit = { required = {} },
  Rollback = { required = {} },
  Defer = { required = {}, optional = { "block", "expr" } },
  Return = { required = {}, optional = { "value" } },
  If = { required = { "cond", "then_block" }, optional = { "else_block" } },
  While = { required = { "cond", "body" } },
  For = { required = { "name", "body" }, optional = { "range_start", "range_end", "iter" } },
  Break = { required = {} },
  Continue = { required = {} },
  Match = { required = { "expr", "arms" } },
  Unsafe = { required = { "block" } },
  Spawn = { required = { "block" } },
  Assign = { required = { "name", "value" } },
  MemberAssign = { required = { "object", "property", "value" } },
  IndexAssign = { required = { "object", "index", "value" } },
  DerefAssign = { required = { "name", "value" } },
  ExprStmt = { required = { "expr" } },
  WithinBlock = { required = { "duration", "block" } },
  DuringBlock = { required = { "condition", "block" } },
  DebugOwnership = { required = { "rules" } },

  TuplePattern = { required = { "names" } },
  IdentPattern = { required = { "name" } },

  Bool = { required = { "value" } },
  Nil = { required = {} },
  Number = { required = { "value" } },
  String = { required = { "value" } },
  Array = { required = { "elements" } },
  Identifier = { required = { "name" } },
  Binary = { required = { "op", "left", "right" } },
  Unary = { required = { "op", "expr" } },
  Borrow = { required = { "expr", "mutable" } },
  Deref = { required = { "expr" } },
  Call = { required = { "callee", "args" }, optional = { "type_args" } },
  Member = { required = { "object", "property" } },
  Index = { required = { "object", "index" } },
  Slice = { required = { "object", "start" }, optional = { "finish" } },
  Try = { required = { "expr" } },
  Generic = { required = { "expr", "type_args" } },
  StructLit = { required = { "name", "fields" } },

  TemporalValue = { required = { "name", "value", "lifetime" } },
  OwnershipTrace = { required = { "variable", "event" } },
}

return schema
