-- GENERATED BY tools/gen_cmm_shim.py -- DO NOT EDIT BY HAND.
--
-- Runtime entry points whose C signature returns void.  A Cmm call to
-- one of these must be emitted as a statement, not bound to a result.

return {
  void_fns = {
    ["rex_collections_map_put"] = true,
    ["rex_collections_set"] = true,
    ["rex_collections_set_add"] = true,
    ["rex_collections_vec_push"] = true,
    ["rex_collections_vec_set"] = true,
    ["rex_deref_assign"] = true,
    ["rex_drop"] = true,
    ["rex_free"] = true,
    ["rex_os_set_args"] = true,
    ["rex_ownership_check"] = true,
    ["rex_ownership_cleanup"] = true,
    ["rex_ownership_debug_disable"] = true,
    ["rex_ownership_debug_enable"] = true,
    ["rex_ownership_trace"] = true,
    ["rex_panic"] = true,
    ["rex_print"] = true,
    ["rex_println"] = true,
    ["rex_sender_send"] = true,
    ["rex_struct_set"] = true,
  },
}
