-- Runtime builtin name tables shared by every code-generation backend.
--
-- These map Rex names to the C runtime symbols in `runtime_c/`.  Both the C
-- and Cmm backends must agree exactly: a drift here surfaces only as an
-- undefined symbol at link time, so the tables live in one place instead of
-- being copied into each backend.
return {
builtins = {
  println = "rex_println",
  print = "rex_print",
  channel = "rex_channel",
  spawn = "rex_spawn",
  sleep = "rex_sleep",
  now_ms = "rex_now_ms",
  format = "rex_format",
  Ok = "rex_ok",
  Err = "rex_err",
  alloc = "rex_alloc",
  free = "rex_free",
  box = "rex_box",
  unbox = "rex_unbox",
  drop = "rex_drop",
  sqrt = "rex_sqrt",
  abs = "rex_abs",
},
module_builtins = {
  io = {
    println = "rex_println",
    print = "rex_print",
    read_file = "rex_io_read_file",
    write_file = "rex_io_write_file",
    read_line = "rex_io_read_line",
    read_lines = "rex_io_read_lines",
    write_lines = "rex_io_write_lines",
  },
  fs = {
    exists = "rex_fs_exists",
    mkdir = "rex_fs_mkdir",
    remove = "rex_fs_remove",
    is_dir = "rex_fs_is_dir",
    read_dir = "rex_fs_read_dir",
    copy = "rex_fs_copy",
    move = "rex_fs_move",
  },
  thread = { channel = "rex_channel", wait_all = "rex_wait_all" },
  time = {
    sleep = "rex_sleep",
    sleep_s = "rex_sleep_s",
    now_ms = "rex_now_ms",
    now_s = "rex_now_s",
    now_ns = "rex_now_ns",
    since = "rex_time_since",
  },
  fmt = {
    format = "rex_format",
    pad_left = "rex_fmt_pad_left",
    pad_right = "rex_fmt_pad_right",
    join = "rex_fmt_join",
    fixed = "rex_fmt_fixed",
    hex = "rex_fmt_hex",
    bin = "rex_fmt_bin",
  },
  text = {
    initials = "rex_text_initials",
    lower_ascii = "rex_text_lower_ascii",
    pad_left = "rex_text_pad_left",
    pad_right = "rex_text_pad_right",
    trim = "rex_text_trim",
    trim_start = "rex_text_trim_start",
    trim_end = "rex_text_trim_end",
    split_words = "rex_text_split_words",
    starts_with = "rex_text_starts_with",
    ends_with = "rex_text_ends_with",
    contains = "rex_text_contains",
    replace = "rex_text_replace",
    ["repeat"] = "rex_text_repeat",
    lines = "rex_text_lines",
    upper_ascii = "rex_text_upper_ascii",
    is_empty = "rex_text_is_empty",
    len_bytes = "rex_text_len_bytes",
    index_of = "rex_text_index_of",
    last_index_of = "rex_text_last_index_of",
  },
  mem = {
    alloc = "rex_alloc",
    free = "rex_free",
    box = "rex_box",
    unbox = "rex_unbox",
    drop = "rex_drop",
  },
  math = { sqrt = "rex_sqrt", abs = "rex_abs", eval = "rex_math_eval" },
  collections = {
    vec_new = "rex_collections_vec_new",
    vec_push = "rex_collections_vec_push",
    vec_get = "rex_collections_vec_get",
    vec_set = "rex_collections_vec_set",
    vec_len = "rex_collections_vec_len",
    vec_insert = "rex_collections_vec_insert",
    vec_pop = "rex_collections_vec_pop",
    vec_clear = "rex_collections_vec_clear",
    vec_sort = "rex_collections_vec_sort",
    vec_slice = "rex_collections_vec_slice",
    vec_from = "rex_collections_vec_from",
    vec_find = "rex_collections_vec_find",
    vec_any = "rex_collections_vec_any",
    vec_all = "rex_collections_vec_all",
    vec_contains = "rex_collections_vec_contains",
    vec_remove_at = "rex_collections_vec_remove_at",
    vec_reverse = "rex_collections_vec_reverse",
    vec_first = "rex_collections_vec_first",
    vec_last = "rex_collections_vec_last",
    vec_join = "rex_collections_vec_join",
    map_new = "rex_collections_map_new",
    map_put = "rex_collections_map_put",
    map_get = "rex_collections_map_get",
    map_remove = "rex_collections_map_remove",
    map_has = "rex_collections_map_has",
    map_keys = "rex_collections_map_keys",
    map_values = "rex_collections_map_values",
    map_items = "rex_collections_map_items",
    map_len = "rex_collections_map_len",
    set_new = "rex_collections_set_new",
    set_add = "rex_collections_set_add",
    set_has = "rex_collections_set_has",
    set_remove = "rex_collections_set_remove",
    set_len = "rex_collections_set_len",
  },
  os = {
    getenv = "rex_os_getenv",
    cwd = "rex_os_cwd",
    platform = "rex_os_platform",
    args = "rex_os_args",
    home = "rex_os_home",
    temp_dir = "rex_os_temp_dir",
  },
  process = {
    run = "rex_process_run",
    capture = "rex_process_capture",
  },
  path = {
    join = "rex_path_join",
    basename = "rex_path_basename",
    dirname = "rex_path_dirname",
    ext = "rex_path_ext",
    stem = "rex_path_stem",
    is_abs = "rex_path_is_abs",
  },
  url = {
    parse = "rex_url_parse",
    encode_component = "rex_url_encode_component",
    decode_component = "rex_url_decode_component",
    join = "rex_url_join",
    with_query = "rex_url_with_query",
  },
  audio = {
    play = "rex_audio_play",
    play_loop = "rex_audio_play_loop",
    stop = "rex_audio_stop",
    supports = "rex_audio_supports",
    set_volume = "rex_audio_set_volume",
    volume = "rex_audio_get_volume",
  },
  log = {
    debug = "rex_log_debug",
    info = "rex_log_info",
    warn = "rex_log_warn",
    error = "rex_log_error",
    set_level = "rex_log_set_level",
    level = "rex_log_get_level",
  },
  net = { tcp_connect = "rex_net_tcp_connect", udp_socket = "rex_net_udp_socket" },
  http = { get = "rex_http_get", get_status = "rex_http_get_status", get_json = "rex_http_get_json" },
  random = {
    seed = "rex_random_seed",
    int = "rex_random_int",
    float = "rex_random_float",
    bool = "rex_random_bool",
    choice = "rex_random_choice",
    shuffle = "rex_random_shuffle",
    range = "rex_random_range",
  },
  json = { encode = "rex_json_encode", encode_pretty = "rex_json_encode_pretty", decode = "rex_json_decode" },
  result = {
    Ok = "rex_ok",
    Err = "rex_err",
    is_ok = "rex_result_is_ok",
    is_err = "rex_result_is_err",
    unwrap_or = "rex_result_unwrap_or",
    unwrap_or_else = "rex_result_unwrap_or_else",
    ok_or = "rex_result_ok_or",
    expect = "rex_result_expect",
  },
  ui = {
    begin = "rex_ui_begin",
    ["end"] = "rex_ui_end",
    redraw = "rex_ui_redraw",
    clear = "rex_ui_clear",
    key_space = "rex_ui_key_space",
    key_up = "rex_ui_key_up",
    key_down = "rex_ui_key_down",
    key_code = "rex_ui_key_code",
    key_is_down = "rex_ui_key_is_down",
    key_pressed = "rex_ui_key_pressed",
    key_released = "rex_ui_key_released",
    mouse_x = "rex_ui_mouse_x",
    mouse_y = "rex_ui_mouse_y",
    mouse_down = "rex_ui_mouse_down",
    mouse_pressed = "rex_ui_mouse_pressed",
    mouse_released = "rex_ui_mouse_released",
    mouse_is_down = "rex_ui_mouse_is_down",
    mouse_pressed_btn = "rex_ui_mouse_pressed_btn",
    mouse_released_btn = "rex_ui_mouse_released_btn",
    scroll_x = "rex_ui_scroll_x",
    scroll_y = "rex_ui_scroll_y",
    label = "rex_ui_label",
    text = "rex_ui_text",
    rect = "rex_ui_rect",
    button = "rex_ui_button",
    checkbox = "rex_ui_checkbox",
    radio = "rex_ui_radio",
    textbox = "rex_ui_textbox",
    slider = "rex_ui_slider",
    progress = "rex_ui_progress",
    switch = "rex_ui_switch",
    select = "rex_ui_select",
    combo = "rex_ui_combo",
    menu = "rex_ui_menu",
    tabs = "rex_ui_tabs",
    row = "rex_ui_layout_row",
    column = "rex_ui_layout_column",
    grid = "rex_ui_layout_grid",
    newline = "rex_ui_newline",
    row_end = "rex_ui_row_end",
    clip_begin = "rex_ui_clip_begin",
    clip_end = "rex_ui_clip_end",
    spacing = "rex_ui_spacing",
    padding = "rex_ui_padding",
    scroll_begin = "rex_ui_scroll_begin",
    scroll_end = "rex_ui_scroll_end",
    enabled = "rex_ui_enabled",
    invert = "rex_ui_invert",
    titlebar_dark = "rex_ui_titlebar_dark",
    theme_dark = "rex_ui_theme_dark",
    theme_light = "rex_ui_theme_light",
    theme_custom = "rex_ui_theme_custom",
    image_load = "rex_ui_image_load",
    image_w = "rex_ui_image_w",
    image_h = "rex_ui_image_h",
    image = "rex_ui_image",
    image_rot = "rex_ui_image_rot",
    image_region = "rex_ui_image_region",
    play_sound = "rex_ui_play_sound",
  },
},
}
